apiVersion: v1
kind: ConfigMap
metadata:
  name: easyshop-config
  namespace: easyshop
data:
  MONGODB_URI: "mongodb://mongodb-0.mongodb-service.easyshop.svc.cluster.local:27017/easyshop"
  REDIS_URI: "redis://easyshop-redis.easyshop.svc.cluster.local:6379"
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "http://15.206.92.142/api" 
  NEXTAUTH_URL: "http://15.206.92.142"  
  NEXTAUTH_SECRET: "jQ7Qi4dXzzRkyqtoZvErOt49oAm9ZrX0v7o9I49XTWo="
  JWT_SECRET: "7be03ef81afca2ee21e76b0a7dcd0136a03718be6bae560b9574d7ccd1d7a14f"
