apiVersion: v1
kind: Secret
metadata:
  name: easyshop-secrets
  namespace: easyshop
type: Opaque
stringData:
  JWT_SECRET: "7be03ef81afca2ee21e76b0a7dcd0136a03718be6bae560b9574d7ccd1d7a14f"
  NEXTAUTH_SECRET: "jQ7Qi4dXzzRkyqtoZvErOt49oAm9ZrX0v7o9I49XTWo="
